### ISSUE TITLE
Version 6.21 can't be patched

### ISSUE THREAD

**Issue by PossibleReference** [RealProHenis/ButterflyLauncher#11]
I wanna play the butterfly event, but it doesn't work for some reason.

**Comment by RealProHenis** [comment]
I've encountered this error before too. For some reason, 6.21 and I think another 6.x version cannot be patched. I tried launching a 6.21 with the Game Server type (which doesn't require the headless patch) and the process still crashed. My guess is there's either something wrong with the 6.21 version of Fortnite that's available for download, or the Project Reboot game server DLL isn't compatible with this version of Fortnite :/ Sorry about that, but unfortunately I don't think there's anything I can do
