### ISSUE TITLE
Version 12.61 Battle Pass seems to be unpurchasable

### ISSUE THREAD

**Issue by PossibleReference** [RealProHenis/ButterflyLauncher#13]
Don't really need to explain much

**Comment by RealProHenis** [comment]
Hmmm, I launched 12.61 and noticed that too. Not too sure why that's happening but I'll look into it

**Comment by RealProHenis** [comment]
After messaging Lawin, (the developer of the backend process that allows these old versions of Fortnite to launch) he told me that unfortunately there's no support for the Battle Pass on 12.61

**Comment by PossibleReference** [comment]
What about the other Chapter 2 Season 2 versions? Do they work?

**Comment by RealProHenis** [comment]
Lawin says purchasing the Battle Pass only works on Chapter 1. Specifically, it only works from Chapter 1, Season 2 to Season 10
