### ISSUE TITLE
Version 4.2 can't log in

### ISSUE THREAD

**Issue by PossibleReference** [RealProHenis/ButterflyLauncher#17]
Don't really know how to explain this. It has a different error message every time.

**Comment by PossibleReference** [comment]
Sometimes, it goes to a blank log in screen

**Comment by RealProHenis** [comment]
Unfortunately, Chapter 1 Season 4 is known for its weird login issues. There is a workaround for this, but it's weirdly complicated (Im not even sure how to do it) and not something I can easily implement into the Butterfly Launcher
