### ISSUE TITLE
Doesnt show apply for me when I go into my settings

### ISSUE THREAD

**Issue by mattidgt** [RealProHenis/ButterflyLauncher#2]
doesnt let me full screen or adjust it, just lets me drag it around... cuts it off right after the item shop customization. 
![Screenshot_20230221_115306](https://user-images.githubusercontent.com/126045823/220525459-a1099971-b321-4d2b-b8ac-363cca77c018.png)

**Comment by RealProHenis** [comment]
Hey mattidgt!

I wasn't able to re-create the issue you're having, so it's hard to diagnose, but I tried adding a check when the Settings window opens that should force it to open with the correct dimensions. 

Go ahead and open the Butterfly Launcher, and it should prompt you to download the latest version (v1.0.2.1) that hopefully fixes the issue! Lmk if you still have problems :)

**Comment by RealProHenis** [comment]
Ok, I don't think my recent updates fixed your issue, but the good news is I think I found the issue. Out of curiousity, what is the resolution of the screen you're opening the Butterfly Launcher on?

**Comment by mattidgt** [comment]
1360x768
The problem is fixed but now I barely see the apply button but I think I
can click it now. If it’s possible you should add a way to scroll on the
page.

**Comment by RealProHenis** [comment]
Ok, thanks! I just pushed out another update. Lmk if that fixes it completely. If not, I might have an idea now judging by your screen resolution. And just to be sure, your screen resolution is 1360x768 and not 1366x768?
