### ISSUE TITLE
Fix unsupported builds somehow?

### ISSUE THREAD

**Issue by PossibleReference** [RealProHenis/ButterflyLauncher#20]
I really wanna play the butterfly event, but the game doesn't support the version that it took place in. I really want it to be fixed if possible.

**Comment by RealProHenis** [comment]
Hey PossibleReference, unfortunately the butterfly event, v6.21, doesn't seem to work with the Project Reboot game server. (https://github.com/Milxnor/Project-Reboot-3.0) I have very little understanding of how Project Reboot works so I'm not sure how to fix it :/
