### ISSUE TITLE
Can't select skin?

### ISSUE THREAD

**Issue by theman12222** [RealProHenis/ButterflyLauncher#24]
Hi, I'm playing on version 12.41 but when I try to select my skin nothing happens? Is there something else I need to do? thanks

**Comment by CoolGuy1234yt** [comment]
You can use newer builds like 14.60 and get the cosmetics to 12.41

**Comment by RealProHenis** [comment]
> Hi, I'm playing on version 12.41 but when I try to select my skin nothing happens? Is there something else I need to do? thanks

Hey theman12222,
You're right, it seems that selecting a skin in 12.41 is not possible, but CoolGuy1234yt's suggestion does seem to work. If you open another Chapter 2 version (like 14.60) and select a skin, you can then close out of 14.60 and re-open 12.41 and you'll be wearing the skin that you selected in 14.60
