### ISSUE TITLE
Cheat command does not work in console

### ISSUE THREAD

**Issue by TeamMePlsBe** [RealProHenis/ButterflyLauncher#28]
I have been having this issue with Project Reboot launcher and Butterfly Launcher, I am pretty sure it is caused by the reboot.dll file. On Builds that I have tested (7.40, 12.21, 12.41, 12.61) the cheat command will work the first time you load up the build on a computer. When you relaunch though, the command doesn't say it was not found but it doesn't do anything.  I have recompiled the DLL before from the GitHub repo but the issue persists. I don't know enough about how the DLLs work to understand why it only works on the first try but I have attempted deleting files and resetting stuff but it still does not work after that first launch on Season 7 build and Season 12 build. If you have any idea what could be causing this please let me know, or if this is more of a problem with the Reboot DLL and I should contact them instead.

**Comment by RealProHenis** [comment]
Hey TeamMePlsBe, I'm happy to help you resolve this!

When you say that cheat commands only work the first time you load up the build, does that mean they only work one time and then you'd have to restart Fortnite to use the command?

Also, what command are you having this issue with?

**Comment by TeamMePlsBe** [comment]
Oh wait, I just realized something. If you don't press F2 before executing a cheat command it doesn't work. I fixed my issue now. 😊
